# Generated by Django 3.2.25 on 2024-11-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0004_auto_20241031_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastGeneratedUID',
        ),
    ]
