# Generated by Django 4.2.17 on 2024-12-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0005_ccvdownstream_ccvupstream_compositeledger_filtermetadata_filterrecord_metadataledger_supplementalled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LCVTermDjangoModel',
        ),
    ]
