# Generated by Django 3.2.25 on 2024-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0010_auto_20241106_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='uidrequesttoken',
            name='uid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
